name: video
description: 'Video Player'
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5 
  media_kit_libs_video: ^1.0.5

  path: ^1.8.2
  file_picker: ^8.1.3
  path_provider: ^2.0.14
  http: ">=0.13.0 <2.0.0"
  universal_platform: ^1.0.0+1
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
